type: 'application'
language: 'python'

project:
  name: 'serverCodeGenie'
  description: 'A FastAPI backend service.'
  channel: '#fastapi'
  owner: 'backend.team'
  maintainers: ['backend.maintainer']

tasks:
  serve:
    command: 'uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    inputs:
      - '**/*.py'
  build:
    command: 'python -m compileall .'
    inputs:
      - '**/*.py'
    outputs:
      - '__pycache__'
